### ISSUE TITLE
Great job, Chen!

### ISSUE THREAD

**Issue by xulihang** [OmegaT-L10N/zh_CN#1]
Hi @WynnChen ,

I previously managed this Chinese localization project. I reviewed your work and I think you have done a great job. Better than me.

Could you write down a translation guide? Like there should be a space between Chinese characters and Latin letters and how should a term be translated.

I also found some problems in your translation:

1. In this segment "&Do not unescape Unicode literals (\uXXXX)"，"unescape" should be translated as "转义".
2. Locale seems a non-translatable. So "Magento CE Locale CSV" should not be translated as "Magento CE 语言环境 CSV"
3. &Align Files..., Align should be translated as "对齐".

Terms are difficult to manage in a team project with OmegaT. Are there some terms that you think should be discussed and recorded in a glossary table like below?

Glossary:
source language	原文语种
target language	译文语种

**Comment by WynnChen** [comment]
hi，我直接写中文了，希望不会有问题。
先说明一下一些背景因素：
之前我并不知道这个库的存在，我是直接从 omegaT 的主 git 库拉取了内容之后完整翻译了 Bundle.properties 之后在那边提交了 PR，然后才被邀请加入这个库。目前我只是简单的把把之前的对 Bundle.properties 的翻译项目合并进入这里，其他的内容都尚未进行或刚刚开始，包括其他需要翻译的文件、词汇表条目等，稍后我会逐步尝试将这些内容补充上来。

关于您所指出的几个问题：
1. "escape"才是“转义”，"unescape"应当是对转义的逆操作，即从转义后得到的序列反向得到转义之前的字符/字符串，直译可以译为“反转义”或“逆转义”之类，但这样很拗口，因此参考了很多其他地方对 unescape 的翻译后折中选择了“解码”作为中译，兼顾含义和易读性。
2. 此处的 Locale 的翻译参考了 windows 操作系统等一些地方对 Locale 的翻译，我个人对这一段的解读是“Magento CE 用来做 Locale 的 CSV”，所以认为翻成中文会更直观一些。
3. Align Files 这个确实是个难译的点，我也中途调整了很多次，个人觉得翻译成“对齐”不太贴切，但目前我使用的翻译也并不理想。有待商榷，如果确实想不到更好的方案我同意将其改回“对齐”。

另外，我有个疑问，希望能得到解答。OmegaT 主 git/svn 库和发布出去的版本中的 Bundle-zh_CN.properties 是非常滞后的，按 commit 备注看大概只是 v3.0.1 的内容。而从这个 L10N 项目得到的译文结果要远远领先于此，只有少量内容没有翻译，也就是说这里的翻译成果并没有及时体现到 OmegaT
 中，而且这个差距是非常长的。所以我疑惑的是这个 L10N 的翻译结果是通过怎样的机制体现到 OmegaT 主库中呢？之前我对比了其它语言的 L10N 库后认为是通过 target 目录来体现结果合并回 OmegaT 那边（例如 ru、tr 等语言），但鉴于您又删掉了 targat 目录，也许是我弄错了，求解惑。

**Comment by xulihang** [comment]
才发现是unescape，这样的确解码比较好。它的意思其实是显示中文，而不是unicode。

Align翻译成对齐的话主要是其它的CAT软件都采用的这个说法。其实OmegaT的术语和其它CAT软件还是有挺多不同的，比如segment，Trados和memoQ里翻译为句段，我们这里翻译为片段。还有auto-propagation，我主张翻译为自动填充，不过一般的CAT软件都翻译为自动传播。

如何体现到 OmegaT 主库中 (how to synchronize localized files to the OmegaT main repository )，这个得问 @kosivantsov ，主要是他进行管理的。一般是我们通知他译文质量达到要求了，可以发布了，他就会把翻译的文件手动同步过去。而英文原版文件应该都是最新的。

这是他之前发的邮件，版本要更新了，问大家翻译得怎么样了，可以的话跟他说一下：


>If the OmegaT localisation project where you're involved in hadn't been updated lately, but you have been working on it, and some parts are now ready or almost ready for the release, it would be great if you finalised it to be included in 4.1.5.
>
>I'm expecting a brief message from you to be informed as to what has been updated and is now release-ready. In case there's nothing from your project to be included in the upcoming release, no message is necessary. I hope to get your messages by the end of Wednesday.

**Comment by WynnChen** [comment]
ok，align 这个我回头会改成对齐。 ps. 关于“自动传播”这个，因为还有个“auto-populated”需要翻译成自动填充，所以“auto-propagation”还是翻译成自动传播比较好。
关于git库里的 /target 目录，如果没有特别的规则要求的话我建议保留着，因为可以直接拉下来看翻译文件，相对方便一点，我这边有几个朋友会时不时 review 我的各种翻译项目的翻译结果，但大多不会大动干戈地装 OmegaT，所以有一个可以直接看到结果的文件的方案会比较方便。L10N 其他好几个语言的库内也都保留着 /target。

**Comment by xulihang** [comment]
好的，UI的翻译你觉得可以了就给kos发封邮件，让他更新到OmegaT的库里吧。

**Comment by WynnChen** [comment]
没找着他的邮件地址……难道是 l10n@omegat.org 这个？

**Comment by xulihang** [comment]
这个应该也能联系到，个人的话是这个：kos.ivantsov at gmail.com

**Comment by kosivantsov** [comment]
So I take it's finally ready to be committed to /trunk?

**Comment by WynnChen** [comment]
@kosivantsov The translation for UI (Bundle.properties -> Bundle_zh_CN.properties) is finally ready. The other parts are under working. So if you can, please merge this file into /trunk first, at least we can have a complete Chinese interface. Thanks!

**Comment by kosivantsov** [comment]
This was released in 4.2.0
