### ISSUE TITLE
Continuous integration for website and docs localization 

### ISSUE THREAD

**Issue by xulihang** [OmegaT-L10N/zh_CN#2]
@kosivantsov 

I find it inconvenient to see the translation results for website and documentation as we have to build our own environment. Is there a continuous integration solution that when a new translation is uploaded, the website and docs will be updated immediately.

I have built one using git hooks: <http://xulihang.me:8080/zh_CN/>, but not easy to use.

**Comment by kosivantsov** [comment]
@xulihang 
There nothing of that sort currently available or planned. If you want to test your translation, you'll have to set up a local environment that will build the website and/or docs using your localised data. Automatic commits to upstream and generation of documentation and website content wouldn't be desirable as it would mean that at any given point there could be "halfbaked" user documentation and webpages available to the end users.

The finished website data is committed manually to https://github.com/omegat-org/omegat-website. You may ask @briacp about specifics of the website generation.

The documentation build process is described here: https://sourceforge.net/p/omegat/svn/HEAD/tree/trunk/doc_src/Readme.txt
